adds live plotter python script
KodlabPenn/kodlab_mjbots_sdk pull request #13
Opened 2022-06-15 02:02 UTC by jdcaporale

Add a live plotter example to the kodlab_mjbots_sdk. Not perfect (the plot takes time and can't read LCM in that time so there are drops) but useful functionality

2022-06-18 21:03 UTC, ethanmusser approved these changes

2022-06-18 21:03 UTC, ethanmusser commented on python_scripts/live_motor_plotter.py
> +class BlitManager:
Class template pulled from https://matplotlib.org/stable/tutorials/advanced/blitting.html

2022-06-18 21:19 UTC, ShaneRozenLevy requested changes
To make this really useful you should make it an abstract class that can be inherited, that way if you want to make multiple live plotting scripts you don't have to copy code. Beyond that LGTM.

2022-06-27 23:48 UTC, jdcaporale commented
@ShaneRozenLevy  ok if I merge in as is and add an issue? Agree it would be more useful, but in case people need some live plotting now I feel like it should be available.

2022-06-27 23:51 UTC, ShaneRozenLevy commented
Looking more closely, the `BlitManager` is general purpose. Just put it in a different file and it lgtm

2022-07-31 23:35 UTC, merged